controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
fetch_formation_assurer_details:
    path: /fetch-formation-assurer-details/{id}
    controller: App\Controller\FormationAssurerController::fetchFormationAssurerDetails
    methods: ['GET']