controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
fetch_formation_assurer_details:
    path: /fetch-formation-assurer-details/{id}
    controller: App\Controller\FormationAssurerController::fetchFormationAssurerDetails
    methods: ['GET']
ajouter_piece_jointe:
    path: '/ajouter-piece-jointe/{id}'
    controller: 'App\Controller\FactureController::ajouterPieceJointe'
    methods: [ 'POST' ]

generate_pdf:
    path: /generate-pdf
    controller: App\Controller\FactureController::generatePdf

generatefactureAchat_pdf:
    path: /generatefactureAchat_pdf
    controller: App\Controller\FactureAchatController::generatefactureAchat_pdf

generatenoteHonoraire_pdf:
    path: /generatenoteHonoraire_pdf
    controller: App\Controller\NoteHonoraireController::generatenoteHonoraire_pdf